<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="secretVotingScheme" nsURI="http://www.example.org/secretVotingScheme"
    nsPrefix="secretVotingScheme">
  <eClassifiers xsi:type="ecore:EClass" name="Voter" eSuperTypes="#//MessageListener">
    <eOperations name="fillBallot"/>
    <eOperations name="sendBallotToAdmin"/>
    <eOperations name="sendVoteToCounter"/>
    <eOperations name="openVote"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ballot" eType="#//Ballot"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymouschannel" lowerBound="1"
        eType="#//AnonymousChannel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Administrator">
    <eOperations name="signBallot"/>
    <eOperations name="checkEligibility"/>
    <eOperations name="publishVotersList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blindSignatureKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="votersList" upperBound="-1"
        eType="#//Voter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Counter" eSuperTypes="#//MessageListener">
    <eOperations name="collectBallots"/>
    <eOperations name="publishBallotsList"/>
    <eOperations name="openVotes"/>
    <eOperations name="countVotes"/>
    <eOperations name="announceResults"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ballotsList" upperBound="-1"
        eType="#//Ballot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="results" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymouschannel" lowerBound="1"
        eType="#//AnonymousChannel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ballot">
    <eOperations name="encryptVote"/>
    <eOperations name="signBallot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encryptedVote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" eType="#//Signature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cryptfacade" eType="#//CryptoFacade"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eOperations name="sign"/>
    <eOperations name="verify"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousChannel">
    <eOperations name="sendMessage"/>
    <eOperations name="receiveMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagemanager" eType="#//MessageManager"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CryptoFacade">
    <eOperations name="encrypt"/>
    <eOperations name="decrypt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageManager">
    <eOperations name="subscribe"/>
    <eOperations name="unsubscribe"/>
    <eOperations name="notifyMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagelistener" upperBound="-1"
        eType="#//MessageListener" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageListener">
    <eOperations name="update"/>
  </eClassifiers>
</ecore:EPackage>
